# syntax=docker/dockerfile:1

ARG REGISTRY=docker.io

ARG OS_BASE=archlinux
ARG OS_VERSION=base-20260906.0.587075@sha256:b944cc65c5f28665dfd5fdbf5ed2997c88f5bb4a0aefac7ee8a7ef01893e5ed9

# Download the dependencies
FROM --platform=${BUILDPLATFORM} ${REGISTRY}/${OS_BASE}:${OS_VERSION} AS base

ARG GID=59999
ARG UID=59999
ARG USER=nonroot
ARG GROUP=nonroot
ARG HOME=/home/${USER}

ENV IS_FULL_INSTALLATION=false
ENV TZ=Europe/Moscow

RUN <<EOF
groupadd --gid ${GID} ${GROUP}
useradd --comment "${USER}" --create-home --shell /bin/bash --uid ${UID} --gid ${GID} ${USER}
pacman-key --init
pacman-key --populate archlinux
EOF
RUN --mount=type=cache,target=/var/cache/pacman/pkg,sharing=locked \
    pacman --refresh --sync && pacman --needed --noconfirm --sync \
        git>=2.55.* \
        make>=4.4.* \
        sudo>=1.9.17.* \
        && \
    printf '%s ALL=(ALL) NOPASSWD:ALL\n' "${USER}" >> /etc/sudoers.d/${USER} && \
    runuser ${USER} --login --command 'printf "make help" >> .bashrc'

USER ${UID}:${GID}

WORKDIR ${HOME}/dotfiles

COPY --link --chown=${UID}:${GID} . .

# DEBUG
FROM base AS debug
ENTRYPOINT ["/bin/bash"]

# Final
FROM base AS final
RUN --mount=type=cache,target=/var/cache/pacman/pkg,sharing=locked \
    --mount=type=secret,id=GITHUB_TOKEN,env=GITHUB_TOKEN,required=false \
    make install
