[tools]
bat = "latest"
cheat = "latest"
delta = "latest"
dive = "latest"
duf = "latest"
dust = "latest"
fd = "latest"
fzf = "latest"
hyperfine = "latest"
jq = "latest"
lazygit = "latest"
neovim = "latest"
ripgrep = "latest"
starship = "latest"
tmux = "latest"
vim = "latest"
yamlfmt = "latest"
yq = "latest"
zoxide = "latest"
