# origin ref: https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md
gui:
  authorColors: {}
  branchColorPatterns: {}
  customIcons:
    filenames: {}
    extensions: {}
  scrollHeight: 2
  scrollPastBottom: true
  scrollOffMargin: 2
  scrollOffBehavior: margin
  tabWidth: 4
  mouseEvents: true
  skipAmendWarning: false
  skipDiscardChangeWarning: true
  skipStashWarning: false
  skipNoStagedFilesWarning: false
  skipRewordInEditorWarning: false
  skipSwitchWorktreeOnCheckoutWarning: false
  sidePanelWidth: 0.3333
  expandFocusedSidePanel: false
  expandedSidePanelWeight: 2
  mainPanelSplitMode: flexible
  enlargedSideViewLocation: left
  wrapLinesInStagingView: true
  useHunkModeInStagingView: true
  language: auto
  timeFormat: 02 Jan 06
  shortTimeFormat: 3:04PM
  theme:
    activeBorderColor:
      - green
      - bold
    inactiveBorderColor:
      - default
    searchingActiveBorderColor:
      - cyan
      - bold
    optionsTextColor:
      - blue
    selectedLineBgColor:
      - blue
    inactiveViewSelectedLineBgColor:
      - bold
    cherryPickedCommitFgColor:
      - blue
    cherryPickedCommitBgColor:
      - cyan
    markedBaseCommitFgColor:
      - blue
    markedBaseCommitBgColor:
      - yellow
    unstagedChangesColor:
      - red
    defaultFgColor:
      - default
  commitLength:
    show: true
  showListFooter: true
  showFileTree: true
  showRootItemInFileTree: true
  fileTreeSortOrder: mixed
  fileTreeSortCaseSensitive: true
  showNumstatInFilesView: true
  showRandomTip: false
  showCommandLog: false
  showBottomLine: false
  showPanelJumps: true
  nerdFontsVersion: "3"
  showFileIcons: true
  commitAuthorShortLength: 2
  commitAuthorLongLength: 17
  commitHashLength: 8
  showBranchCommitHash: false
  showDivergenceFromBaseBranch: none
  commandLogSize: 8
  splitDiff: auto
  screenMode: normal
  border: rounded
  animateExplosion: true
  portraitMode: auto
  portraitModeAutoMaxWidth: 84
  portraitModeAutoMinHeight: 46
  filterMode: substring
  spinner:
    frames:
      - "|"
      - /
      - "-"
      - \
    rate: 50
  statusPanelView: dashboard
  switchToFilesAfterStashPop: true
  switchToFilesAfterStashApply: true
  switchTabsWithPanelJumpKeys: false
git:
  pagers:
    - colorArg: always
      pager: delta --paging=never
      externalDiffCommand: ""
  commit:
    signOff: false
    autoWrapCommitMessage: true
    autoWrapWidth: 72
  merging:
    manualCommit: false
    args: ""
    squashMergeMessage: Squash merge {{selectedRef}} into {{currentBranch}}
  mainBranches:
    - master
    - main
  skipHookPrefix: WIP
  autoFetch: true
  autoRefresh: true
  autoForwardBranches: onlyMainBranches
  fetchAll: true
  autoStageResolvedConflicts: true
  branchLogCmd: git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium {{branchName}} --
  allBranchesLogCmds:
    - git log --graph --all --color=always --abbrev-commit --decorate --date=relative  --pretty=medium
  ignoreWhitespaceInDiffView: false
  diffContextSize: 3
  renameSimilarityThreshold: 50
  overrideGpg: false
  disableForcePushing: false
  commitPrefix: []
  commitPrefixes: {}
  branchPrefix: ""
  parseEmoji: false
  log:
    order: topo-order
    showGraph: always
    showWholeGraph: false
  localBranchSortOrder: date
  remoteBranchSortOrder: date
  truncateCopiedCommitHashesTo: 12
update:
  method: prompt
  days: 14
refresher:
  refreshInterval: 10
  fetchInterval: 60
confirmOnQuit: false
quitOnTopLevelReturn: false
os:
  edit: "$EDITOR {{filename}}"
  editAtLine: "$EDITOR +{{line}} {{filename}}"
  editAtLineAndWait: "$EDITOR {{filename}}"
  editInTerminal: true
  openDirInEditor: ""
  editPreset: ""
  open: ""
  openLink: ""
  copyToClipboardCmd: >
    if [[ "$TERM" =~ ^(screen|tmux) ]]; then
      printf "\033Ptmux;\033\033]52;c;$(printf {{text}} | base64 -w 0)\a\033\\" > /dev/tty
    else
      printf "\033]52;c;$(printf {{text}} | base64 -w 0)\a" > /dev/tty
    fi
  readFromClipboardCmd: ""
  shellFunctionsFile: ""
disableStartupPopups: false
customCommands: []
services: {}
notARepository: prompt
promptToReturnFromSubprocess: false
keybinding:
  universal:
    quit: q
    suspendApp: <ctrl+z>
    return: <esc>
    quitWithoutChangingDirectory: Q
    togglePanel: <tab>
    prevItem: [<up>, k]
    nextItem: [<down>, j]
    prevPage: <c-b>
    nextPage: <c-f>
    scrollLeft: H
    scrollRight: L
    gotoTop: [g, <home>]
    gotoBottom: [G, <end>]
    toggleRangeSelect: v
    rangeSelectDown: <shift+down>
    rangeSelectUp: <shift+up>
    prevBlock: [<left>, h, <backtab>]
    nextBlock: [<right>, l, <tab>]
    jumpToBlock:
      - "1"
      - "2"
      - "3"
      - "4"
      - "5"
    focusMainView: "6"
    nextMatch: "n"
    prevMatch: "N"
    startSearch: /
    moveWordLeft: <alt+left>
    moveWordRight: <alt+right>
    backspaceWord: <ctrl+w>
    forwardDeleteWord: <ctrl+delete>
    optionMenu: "?"
    select: <space>
    goInto: <enter>
    confirm: <enter>
    confirmSuggestion: <enter>
    confirmInEditor: <ctrl-enter>
    remove: d
    new: "n"
    edit: e
    openFile: o
    scrollUpMain: [<pgup>, K, <ctrl+u>]
    scrollDownMain: [<pgdown>, J, <ctrl+d>]
    executeShellCommand: ":"
    createRebaseOptionsMenu: <c-o>
    pushFiles: P
    pullFiles: p
    refresh: R
    createPatchOptionsMenu: <ctrl+p>
    nextTab: "]"
    prevTab: "["
    nextScreenMode: +
    prevScreenMode: _
    undo: z
    redo: Z
    filteringMenu: "!"
    diffingMenu: [W, <ctrl+e>]
    copyToClipboard: Y
    openRecentRepos: <ctrl+r>
    submitEditorText: <enter>
    extrasMenu: "@"
    toggleWhitespaceInDiffView: <ctrl+w>
    increaseContextInDiffView: "}"
    decreaseContextInDiffView: "{"
    increaseRenameSimilarityThreshold: )
    decreaseRenameSimilarityThreshold: (
    openDiffTool: <ctrl+t>
    newWorktree: w
  status:
    checkForUpdate: u
    recentRepos: <enter>
    allBranchesLogGraphReverse: A
    allBranchesLogGraph: a
  files:
    commitChanges: c
    commitChangesWithoutHook: w
    amendLastCommit: A
    commitChangesWithEditor: C
    findBaseCommitForFixup: b
    confirmDiscard: x
    ignoreFile: i
    refreshFiles: r
    stashAllChanges: s
    viewStashOptions: S
    toggleStagedAll: a
    viewResetOptions: D
    fetch: f
    toggleTreeView: T
    openMergeOptions: M
    openStatusFilter: F
    copyFileInfoToClipboard: "y"
    collapseAll: "-"
    expandAll: "="
  branches:
    createPullRequest: o
    viewPullRequestOptions: O
    copyPullRequestURL: "y"
    checkoutBranchByName: c
    forceCheckoutBranch: f
    rebaseBranch: r
    renameBranch: R
    mergeIntoCurrentBranch: M
    moveCommitsToNewBranch: "N"
    viewGitFlowOptions: i
    fastForward: f
    createTag: t
    pushTag: P
    setUpstream: u
    fetchRemote: F
    sortOrder: ","
  commits:
    squashDown: s
    renameCommit: r
    renameCommitWithEditor: R
    viewResetOptions: D
    markCommitAsFixup: f
    createFixupCommit: F
    squashAboveCommits: S
    moveDownCommit: ">"
    moveUpCommit: "<"
    amendToCommit: A
    resetCommitAuthor: a
    pickCommit: p
    revertCommit: t
    cherryPickCopy: C
    pasteCommits: V
    markCommitAsBaseForRebase: B
    tagCommit: T
    checkoutCommit: <space>
    resetCherryPick: '\'
    copyCommitAttributeToClipboard: y
    openLogMenu: m
    openInBrowser: o
    viewBisectOptions: b
    startInteractiveRebase: i
    selectCommitsOfCurrentBranch: "*"
  amendAttribute:
    resetAuthor: a
    setAuthor: A
    addCoAuthor: c
  stash:
    popStash: S
    renameStash: r
  commitFiles:
    checkoutCommitFile: c
  main:
    toggleSelectHunk: a
    pickBothHunks: b
    editSelectHunk: E
  submodules:
    init: i
    update: u
    bulkMenu: b
  commitMessage:
    commitMenu: <ctrl+o>
