---
autoclcker_group: autoclcker
autoclcker_user: autoclcker
autoclcker_comment: ""
autoclcker_is_passwordless_sudo: false

autoclcker_dotfiles_src: "../../../../../."
autoclcker_dotfiles_git: https://github.com/autoclcker/dotfiles.git
autoclcker_dotfiles_dst: "/home/{{ autoclcker_user }}/Desktop/Projects"

autoclcker_become: true
