book_sort_order: by_name
justify_text: false
lookup_command: null
lookup_display: popup
margin: 0
nav_panel_width: null
pdf_enabled: true
pdf_page_layout_mode: single
pdf_pan_shift: 0
pdf_render_mode: scroll
pdf_scale: 0.8050314
pdf_settings_configured: true
synctex_editor: null
theme: "Moonfly"
transparent_background: false
version: 3

epub_column_mode: single
invert_scroll_direction: false
