# Run `bookokrat --print-default-keybindings` to see every default binding
[content]
"<C-c>" = "cancel"
"u" = "toggle_raw_html"

[epub_normal]
"i" = "open_highlight_palette"

[global]
"<Space>a" = "nop"
"<Space>D" = "nop"
"<Space>o" = "nop"
"<Space>s" = "nop"
"<Space>t" = "nop"
"<Space>z" = "nop"
"<C-s>" = "nop"
":" = "open_settings"
"!" = "toggle_reading_history"
"<C-g>" = "toggle_comments_viewer"
"<C-v>" = "toggle_pdf_page_layout"
"<C-z>" = "suspend"
"\\" = "toggle_book_stats"
"o" = "open_external_viewer"
"R" = "toggle_pdf_render_mode"
"s" = "toggle_zen_mode"
"T" = "open_theme_selector"

[nav]
"<C-c>" = "cancel"

[pdf]
"<C-c>" = "cancel"
"I" = "toggle_invert_images"
"t" = "toggle_pdf_theming"
"v" = "enter_visual_mode"

[pdf_normal]
"d" = "nop"
"<C-c>" = "cancel"
"a" = "add_comment"
"i" = "open_highlight_palette"

[popup]
"<C-c>" = "cancel"
"d" = "delete_entry"

[popup.comments]
"d" = "delete_comment"
