---
- name: assert | Test autoclcker_become
  ansible.builtin.assert:
    that:
      - autoclcker_become is boolean
    quiet: true
  when:
    - autoclcker_become is defined

- name: assert | Test autoclcker_comment
  ansible.builtin.assert:
    that:
      - autoclcker_comment is string
    quiet: true
  when:
    - autoclcker_comment is defined

- name: assert | Test autoclcker_is_passwordless_sudo
  ansible.builtin.assert:
    that:
      - autoclcker_is_passwordless_sudo is boolean
    quiet: true
  when:
    - autoclcker_is_passwordless_sudo is defined

- name: assert | Test autoclcker_group
  ansible.builtin.assert:
    that:
      - autoclcker_group is string
      - autoclcker_group is match("^[a-z_][a-z0-9_-]*[$]?$")
    fail_msg: "Please use alphanumeric characters only."
    quiet: true
  when:
    - autoclcker_group is defined

- name: assert | Test autoclcker_user
  ansible.builtin.assert:
    that:
      - autoclcker_user is string
      - autoclcker_user is match("^[a-z_][a-z0-9_-]*[$]?$")
    fail_msg: "Please use alphanumeric characters only."
    quiet: true
  when:
    - autoclcker_user is defined

- name: assert | Test dotfiles localhost sources
  when: autoclcker_dotfiles_src is defined
  block:
    - name: assert | Get src directory status
      ansible.builtin.stat:
        path: "{{ autoclcker_dotfiles_src }}"
      register: autoclcker_src

    - name: assert | Test autoclcker_dotfiles_src
      ansible.builtin.assert:
        that:
          - autoclcker_src.stat.exists
          - autoclcker_src.stat.isdir
        fail_msg: "Please specify the path to the existing directory."
        quiet: true

- name: assert | Test autoclcker_dotfiles_git
  ansible.builtin.assert:
    that:
      - autoclcker_dotfiles_dst is defined
      - autoclcker_dotfiles_git is
        regex("^(https|git|ssh)(:\/\/|@)([\\w\\.-]+)(:|\/)([\\w\\.@\\:\/\\-~]+)(\\.git)?(\/)?$")
    fail_msg: "Please provide a valid Git repository URL."
    quiet: true

- name: assert | Test autoclcker_dotfiles_dst
  ansible.builtin.assert:
    that:
      - autoclcker_dotfiles_dst is defined
      - autoclcker_dotfiles_dst is string
      - autoclcker_dotfiles_dst is match("^[a-zA-Z0-9/_-]*$")
    fail_msg: "Please use the correct directory name."
    quiet: true
