---
- name: Assert | Test autoclcker_become
  ansible.builtin.assert:
    that:
      - autoclcker_become is boolean
    quiet: true
  when:
    - autoclcker_become is defined

- name: Assert | Test autoclcker_mirror
  ansible.builtin.assert:
    that:
      - autoclcker_mirror is defined
      - autoclcker_mirror is string
      - autoclcker_mirror is not none
    quiet: true

- name: Assert | Test group in autoclcker_
  ansible.builtin.assert:
    that:
      - group is defined
      - group is string
      - group is match("^[a-z_][a-z0-9_-]*[$]?$")
    fail_msg: "Please use alphanumeric characters only."
    quiet: true
  loop: "{{ autoclcker_ }}"
  loop_control:
    label: "{{ name }}"

- name: Assert | Test user in autoclcker_
  ansible.builtin.assert:
    that:
      - user is defined
      - user is string
      - user is match("^[a-z_][a-z0-9_-]*[$]?$")
    fail_msg: "Please use alphanumeric characters only."
    quiet: true
  loop: "{{ autoclcker_ }}"
  loop_control:
    label: "{{ name }}"

- name: Assert | Test directory in autoclcker_
  ansible.builtin.assert:
    that:
      - directory is defined
      - directory is string
      - directory is match("^[a-zA-Z0-9/_-]*$")
    fail_msg: "Please use the correct directory name."
    quiet: true
  loop: "{{ autoclcker_ }}"
  loop_control:
    label: "{{ name }}"
