---
- name: install | Copy sources from localhost
  when: autoclcker_dotfiles_src is defined
  tags: molecule-idempotence-notest
  block:
    - name: install | Convert relative path to absolute
      ansible.builtin.set_fact:
        autoclcker_abs_path: "{{ autoclcker_dotfiles_src | realpath }}"

    - name: install | Create local temprorary directory
      ansible.builtin.tempfile:
        state: directory
        suffix: _dotfiles_archive
      register: autoclcker_local_temp
      delegate_to: localhost

    - name: install | Archive local files to temp directory
      community.general.archive:
        path: "{{ autoclcker_abs_path }}"
        dest: "{{ autoclcker_local_temp.path }}/dotfiles.tar.gz"
        mode: "440"
        exclusion_patterns:
          - ".vscode"
          - "**/.gitignore"
          - "**/com.system76.CosmicBackground/*"
          - "**/com.system76.CosmicFiles/*"
          - "**/com.system76.CosmicSettings.Wallpaper/*"
          - "**/com.system76.CosmicSettings/*"
          - "**/community/*"
          - "**/copyq/.copyq_s"
          - "**/pinned_workspaces"
          - "**/tmux/plugins/*"
          - "**/xkb_config"
          - "**/yazi/plugins/*"
        format: gz
      delegate_to: localhost
      no_log: true

    - name: install | Add sources
      ansible.builtin.copy:
        src: "{{ autoclcker_local_temp.path }}/dotfiles.tar.gz"
        dest: "/tmp/dotfiles.tar.gz"
        owner: "{{ autoclcker_user | default('autoclcker') }}"
        group: "{{ autoclcker_group | default('autoclcker') }}"
        mode: "440"
        local_follow: false

    - name: install | Extract sources
      ansible.builtin.unarchive:
        src: "/tmp/dotfiles.tar.gz"
        dest: "{{ autoclcker_dotfiles_dst }}"
        owner: "{{ autoclcker_user | default('autoclcker') }}"
        group: "{{ autoclcker_group | default('autoclcker') }}"
        remote_src: true
        extra_opts:
          - "--preserve-permissions"

    - name: install | Remove local temprorary directory
      ansible.builtin.file:
        path: "{{ autoclcker_local_temp.path }}"
        state: absent
      delegate_to: localhost

- name: install | Download sources from git
  ansible.builtin.git:
    repo: "{{ autoclcker_dotfiles_git }}"
    dest: "{{ autoclcker_dotfiles_dst }}/dotfiles"
    version: "{{ autoclcker_git_branches[ansible_facts['os_family']] }}"
  when: autoclcker_dotfiles_src is not defined

- name: install | Desktop Environment
  tags: [molecule-idempotence-notest, install]
  block:
    - name: install | Create a sudoers NOPASSWD entry for installation
      ansible.builtin.template:
        src: templates/sudoers.j2
        dest: "/etc/sudoers.d/{{ autoclcker_user | default('autoclcker') }}"
        owner: root
        group: root
        mode: '0440'
        validate: '/usr/sbin/visudo --check --file %s'
      vars:
        autoclcker_is_passwordless_sudo: true

    - name: install | Launch installer
      environment:
        GITHUB_TOKEN: "{{ autoclcker_github_token }}"
      community.general.make:
        chdir: "{{ autoclcker_dotfiles_dst }}/dotfiles"
        target: install
        params:
          PWD: "{{ autoclcker_dotfiles_dst }}/dotfiles"
      become: true
      become_user: "{{ autoclcker_user | default('autoclcker') }}"
  always:
    - name: install | Configure sudo access
      ansible.builtin.template:
        src: templates/sudoers.j2
        dest: "/etc/sudoers.d/{{ autoclcker_user | default('autoclcker') }}"
        owner: root
        group: root
        mode: '0440'
        validate: '/usr/sbin/visudo --check --file %s'
