---
- name: request_password | Define autoclcker_owner
  ansible.builtin.set_fact:
    autoclcker_owner: "{{ autoclcker_user | default('autoclcker') }}"

- name: request_password | Get user shadow information
  ansible.builtin.getent:
    database: shadow
    key: "{{ autoclcker_owner }}"
  become: "{{ autoclcker_become | default('true') }}"
  register: autoclcker_shadow

- name: request_password | Force password change on first login
  ansible.builtin.command: chage --lastday 0 "{{ autoclcker_owner }}"
  changed_when: false
  become: "{{ autoclcker_become | default('true') }}"
  when:
    - autoclcker_shadow.ansible_facts.getent_shadow[autoclcker_owner][0] | length == 0
