[window]
decorations     = "None"
dynamic_padding = false
dynamic_title   = true
opacity         = 1.0
startup_mode    = "Maximized"
title           = "Alacritty"

[window.dimensions]
columns = 0
lines   = 0

[scrolling]
history = 100000

[font]
size = 14

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[font.bold]
family = "FiraCode Nerd Font"
style = "SemiBold"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.bold_italic]
family = "Hack Nerd Font"
style = "BoldItalic"

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 0

[colors.primary]
foreground = "#ffffff"
background = "#000000"

[colors.normal]
black = "#000000"
red = "#cd3131"
green = "#0dbc79"
yellow = "#e5e510"
blue = "#2472c8"
magenta = "#bc3fbc"
cyan = "#11a8cd"
white = "#e5e5e5"

[colors.bright]
black = "#666666"
red = "#f14c4c"
green = "#23d18b"
yellow = "#f5f543"
blue = "#3b8eea"
magenta = "#d670d6"
cyan = "#29b8db"
white = "#e5e5e5"

[colors.cursor]
cursor = "#00ffa6"

[colors.vi_mode_cursor]
cursor = "#00ffa6"

[cursor.vi_mode_style]
shape = "block"
blinking = "on"

[mouse]
hide_when_typing = true

[[keyboard.bindings]]
key = "d"
mods = "Alt"
chars = 'printf "\e[1;96m%s\e[0m\n" $'

[[keyboard.bindings]]
key = "g"
mods = "Alt"
chars = ' | grep '

[[keyboard.bindings]]
key = "Key1"
mods = "Control"
chars = "\u001b[49;5u"

[[keyboard.bindings]]
key = "Key2"
mods = "Control"
chars = "\u001b[50;5u"

[[keyboard.bindings]]
key = "Key3"
mods = "Control"
chars = "\u001b[51;5u"

[[keyboard.bindings]]
key = "Key4"
mods = "Control"
chars = "\u001b[52;5u"

[[keyboard.bindings]]
key = "Key5"
mods = "Control"
chars = "\u001b[53;5u"

[[keyboard.bindings]]
key = "Key6"
mods = "Control"
chars = "\u001b[54;5u"

[[keyboard.bindings]]
key = "Key7"
mods = "Control"
chars = "\u001b[55;5u"

[[keyboard.bindings]]
key = "Key8"
mods = "Control"
chars = "\u001b[56;5u"

[[keyboard.bindings]]
key = "Key9"
mods = "Control"
chars = "\u001b[57;5u"

[[keyboard.bindings]]
key = "Tab"
mods = "Control"
chars = "\uE000"

[[keyboard.bindings]]
key = "Insert"
mods = "Shift"
action = "Paste"
