[tools]
ansible-base = "latest"
bat = "latest"
cabal = "latest"
cheat = "latest"
cmake = "latest"
delta = "latest"
dive = "latest"
docker-slim = "latest"
duf = "latest"
dust = "latest"
exa = "latest"
fd = "latest"
fzf = "latest"
ghc = "latest"
git = "latest"
golang = "1.23.1"
golangci-lint = "1.61.0"
hadolint = "latest"
haskell = "9.10.1"
helm = "latest"
helm-diff = "latest"
hyperfine = "latest"
java = "corretto-8.412.08.1"
jq = "latest"
k9s = "latest"
kind = "latest"
kubeconform = "latest"
kubectl = "latest"
kubectx = "latest"
lazygit = "latest"
lua = "latest"
make = "latest"
maven = "3.6.3"
minikube = "latest"
neovim = "latest"
nodejs = "22.9.0"
pnpm = "latest"
python = "3.12.6"
ripgrep = "latest"
rust = "1.81.0"
shellcheck = "latest"
starship = "latest"
tmux = "latest"
tomcat = "10.1.25"
vim = "latest"
yamlfmt = "latest"
yamllint = "latest"
yarn = "latest"
yq = "latest"
zoxide = "latest"
usage = "latest"
"go:github.com/jesseduffield/lazydocker" = "latest"
"cargo:alacritty" = "latest"

[settings]
experimental = true
disable_hints = ["registry"]
