[tools]
ansible-base = "2.10.17"
bat = "0.24.0"
cabal = "3.12.1.0"
cheat = "4.4.2"
cmake = "3.30.3"
ctop = "0.7.7"
delta = "0.18.2"
dive = "0.12.0"
docker-slim = "1.40.9"
duf = "0.8.1"
dust = "1.1.1"
exa = "0.10.1"
fd = "10.2.0"
fzf = "0.53.0"
ghc = "9.10.1"
git = "2.46.1"
golang = "1.23.1"
golangci-lint = "1.61.0"
hadolint = "2.12.0"
haskell = "9.10.1"
helm = "3.16.1"
helm-diff = "3.9.10"
hyperfine = "1.18.0"
java = "corretto-8.412.08.1"
jq = "1.7.1"
k9s = "0.32.5"
kind = "0.24.0"
kubeconform = "0.6.7"
kubectl = "1.31.1"
kubectx = "0.9.5"
lazygit = "0.44.1"
lua = "5.4.7"
make = "4.4.1"
maven = "3.6.3"
minikube = "1.34.0"
neovim = "0.10.1"
nodejs = "22.9.0"
pnpm = "9.11.0"
python = "3.12.6"
ripgrep = "14.1.1"
rust = "1.81.0"
shellcheck = "0.10.0"
starship = "1.20.1"
tmux = "3.4"
tomcat = "10.1.25"
vim = "9.1.0737"
yamlfmt = "0.13.0"
yamllint = "1.35.1"
yarn = "1.22.22"
yq = "4.44.3"
zoxide = "0.9.6"
usage = "latest"

[settings]
experimental = true
disable_hints = ["registry"]
