[tools]
"cargo:bandwhich" = "latest"
"cargo:bat" = "latest"
"cargo:binsider" = "latest"
"cargo:bluetui" = "latest"
"cargo:du-dust" = "latest"
"cargo:dufs" = "latest"
"cargo:eza" = "latest"
"cargo:fd-find" = "latest"
"cargo:git-delta" = "latest"
"cargo:gping" = "latest"
"cargo:hyperfine" = "latest"
"cargo:jwt-cli" = "latest"
"cargo:kmon" = "latest"
"cargo:onefetch" = "latest"
"cargo:ouch" = "latest"
"cargo:procs" = "latest"
"cargo:resvg" = "latest"
"cargo:ripgrep_all" = "latest"
"cargo:ripgrep" = "latest"
"cargo:sd" = "latest"
"cargo:systemctl-tui" = "latest"
"cargo:tealdeer" = "latest"
"cargo:timr-tui" = "1.3.1"
"cargo:yazi-cli" = "latest"
"cargo:yazi-fm" = "latest"
"cargo:zoxide" = "latest"
"go:github.com/charmbracelet/glow" = "latest"
"go:github.com/go-delve/delve/cmd/dlv" = "latest"
"go:github.com/google/yamlfmt/cmd/yamlfmt" = "latest"
"go:github.com/jesseduffield/lazydocker" = "latest"
"go:github.com/jesseduffield/lazygit" = "latest"
"go:github.com/jorgerojas26/lazysql" = "latest"
"go:github.com/maaslalani/draw" = "latest"
"go:github.com/Macmod/godap" = "latest"
"go:github.com/mikefarah/yq/v4" = "latest"
"go:github.com/mr-karan/doggo/cmd/doggo" = "latest"
"go:github.com/reproducible-containers/diffoci/cmd/diffoci" = "latest"
"go:github.com/tomnomnom/gron" = "latest"
"npm:@angular/cli" = "latest"
"npm:ts-node" = "latest"
"npm:typescript" = "latest"
"pipx:ansible-core" = "latest"
"pipx:ansible-creator" = "latest"
"pipx:ansible-lint" = "latest"
"pipx:ansible-navigator" = "latest"
"pipx:httpie" = "latest"
"pipx:ipython" = "latest"
"pipx:thefuck" = { version = "latest", pipx_args = "--python 3.11.9" }
"pipx:trash-cli" = "latest"
"ubi:clangd/clangd" = "latest"
"ubi:jgm/pandoc" = "latest"
"ubi:jqlang/jq" = "latest"
"ubi:junegunn/fzf" = "latest"
"ubi:muesli/duf" = "latest"
"ubi:Syllo/nvtop" = "latest"
btop = "latest"
cheat = "latest"
fastfetch = "latest"
ffmpeg = "latest"
imagemagick = "latest"
neovim = "latest"
starship = "latest"
tmux = "latest"
usage = "latest"
vim = "9.1.1680"

[settings]
disable_hints = ["registry"]
experimental = true
not_found_auto_install = false
plugin_autoupdate_last_check_duration = '0'

[settings.cargo]
binstall = true

[env]
BINSTALL_DISABLE_TELEMETRY = true
