[tools]
"cargo:alacritty" = "latest"
"cargo:eza" = "latest"
"cargo:gping" = "latest"
"cargo:onefetch" = "latest"
"cargo:procs" = "latest"
"cargo:sd" = "latest"
"cargo:tealdeer" = "latest"
"go:github.com/go-delve/delve/cmd/dlv" = "latest"
"go:github.com/jesseduffield/lazydocker" = "latest"
"go:github.com/mr-karan/doggo/cmd/doggo" = "latest"
"npm:@angular/cli" = "latest"
"pipx:ansible-core" = "latest"
"pipx:ansible-creator" = "latest"
"pipx:ansible-lint" = "latest"
"pipx:cookiecutter" = "latest"
"pipx:httpie" = "latest"
"pipx:ipython" = "latest"
"pipx:ranger-fm" = "latest"
"pipx:thefuck" = { version = "latest", pipx_args = "--fetch-missing-python --python 3.11" }
tomcat = "9.0.68"
usage = "latest"

[settings]
disable_hints = ["registry"]
experimental = true
