[tools]
"cargo:alacritty" = "latest"
"cargo:bat" = "latest"
"cargo:du-dust" = "latest"
"cargo:eza" = "latest"
"cargo:fd-find" = "latest"
"cargo:git-delta" = "latest"
"cargo:gping" = "latest"
"cargo:hyperfine" = "latest"
"cargo:onefetch" = "latest"
"cargo:ouch" = "latest"
"cargo:procs" = "latest"
"cargo:ripgrep_all" = "latest"
"cargo:ripgrep" = "latest"
"cargo:sd" = "latest"
"cargo:tealdeer" = "latest"
"cargo:yazi-cli" = "latest"
"cargo:yazi-fm" = "latest"
"cargo:zoxide" = "latest"
"go:github.com/charmbracelet/glow" = "latest"
"go:github.com/go-delve/delve/cmd/dlv" = "latest"
"go:github.com/google/yamlfmt/cmd/yamlfmt" = "latest"
"go:github.com/jesseduffield/lazydocker" = "latest"
"go:github.com/jesseduffield/lazygit" = "latest"
"go:github.com/mikefarah/yq/v4" = "latest"
"go:github.com/mr-karan/doggo/cmd/doggo" = "latest"
"go:github.com/reproducible-containers/diffoci/cmd/diffoci" = "latest"
"npm:@angular/cli" = "latest"
"npm:ts-node" = "latest"
"npm:typescript" = "latest"
"pipx:ansible-core" = "latest"
"pipx:ansible-creator" = "latest"
"pipx:ansible-lint" = "latest"
"pipx:httpie" = "latest"
"pipx:ipython" = "latest"
"pipx:thefuck" = { version = "latest", pipx_args = "--python 3.11.9" }
"ubi:clangd/clangd" = "latest"
"ubi:jgm/pandoc" = "latest"
"ubi:jqlang/jq" = "latest"
"ubi:junegunn/fzf" = "latest"
"ubi:muesli/duf" = "latest"
cheat = "latest"
neovim = "0.10.3"
starship = "latest"
tmux = "latest"
tomcat = "9.0.68"
vim = "latest"

[settings]
disable_hints = ["registry"]
experimental = true
not_found_auto_install = false
