[tools]
"cargo:alacritty" = "latest"
"cargo:eza" = "latest"
"cargo:gping" = "latest"
"cargo:onefetch" = "latest"
"cargo:procs" = "latest"
"cargo:sd" = "latest"
"cargo:tealdeer" = "latest"
"go:github.com/go-delve/delve/cmd/dlv" = "latest"
"go:github.com/jesseduffield/lazydocker" = "latest"
"go:github.com/mr-karan/doggo/cmd/doggo" = "latest"
"pipx:ansible-core" = "latest"
"pipx:ansible-creator" = "latest"
"pipx:ansible-lint" = "latest"
"pipx:cookiecutter" = "latest"
"pipx:httpie" = "latest"
"pipx:ipython" = "latest"
"pipx:ranger-fm" = "latest"
"pipx:thefuck" = { version = "latest", pipx_args = "--fetch-missing-python --python 3.11" }
ant = "1.10.13"
bat = "latest"
cheat = "latest"
cmake = "latest"
delta = "latest"
dive = "latest"
docker-slim = "latest"
duf = "latest"
dust = "latest"
fd = "latest"
fzf = "latest"
golangci-lint = "1.61.0"
hadolint = "latest"
haskell = "9.10.1"
helm = "latest"
helm-diff = "latest"
hyperfine = "latest"
java = "corretto-8.412.08.1"
jq = "latest"
k9s = "latest"
kind = "latest"
kubeconform = "latest"
kubectl = "latest"
kubectx = "latest"
lazygit = "latest"
lua = "latest"
make = "latest"
maven = "3.6.3"
minikube = "latest"
neovim = "latest"
nodejs = "22.9.0"
pnpm = "latest"
python = "3.12.6"
ripgrep = "latest"
shellcheck = "latest"
starship = "latest"
tmux = "latest"
tomcat = "9.0.68"
usage = "latest"
vim = "latest"
yamlfmt = "latest"
yamllint = "latest"
yarn = "latest"
yq = "latest"
zoxide = "latest"

[settings]
disable_hints = ["registry"]
experimental = true
not_found_auto_install = false
