[tools]
"cargo:atac" = "latest"
"cargo:bat" = "latest"
"cargo:binsider" = "latest"
"cargo:bluetui" = "latest"
"cargo:bookokrat" = "latest"
"cargo:du-dust" = "latest"
"cargo:dufs" = "latest"
"cargo:eza" = "latest"
"cargo:fd-find" = "latest"
"cargo:git-delta" = "latest"
"cargo:gping" = "latest"
"cargo:hyperfine" = "latest"
"cargo:jwt-cli" = "latest"
"cargo:kmon" = "latest"
"cargo:onefetch" = "latest"
"cargo:ouch" = "latest"
"cargo:resvg" = "latest"
"cargo:ripgrep_all" = "latest"
"cargo:ripgrep" = "latest"
"cargo:rustnet-monitor" = { version = "latest", postinstall = "date && sudo setcap 'cap_net_raw,cap_bpf,cap_perfmon=eip' $(which rustnet)" }
"cargo:sd" = "latest"
"cargo:systemctl-tui" = "latest"
"cargo:tealdeer" = "latest"
"cargo:timr-tui" = "latest"
"cargo:zoxide" = "latest"
"github:jgm/pandoc" = "latest"
"github:jqlang/jq" = "latest"
"github:junegunn/fzf" = "latest"
"github:muesli/duf" = "latest"
"github:neovide/neovide" = "latest"
"go:github.com/charmbracelet/glow" = "latest"
"go:github.com/go-delve/delve/cmd/dlv" = "latest"
"go:github.com/google/yamlfmt/cmd/yamlfmt" = "latest"
"go:github.com/jesseduffield/lazydocker" = "latest"
"go:github.com/jesseduffield/lazygit" = "latest"
"go:github.com/jorgerojas26/lazysql" = "latest"
"go:github.com/maaslalani/draw" = "latest"
"go:github.com/Macmod/godap" = "latest"
"go:github.com/mikefarah/yq/v4" = "latest"
"go:github.com/mr-karan/doggo/cmd/doggo" = "latest"
"go:github.com/reproducible-containers/diffoci/cmd/diffoci" = "latest"
"go:github.com/tomnomnom/gron" = "latest"
"npm:@angular/cli" = "latest"
"npm:ts-node" = "latest"
"pipx:ansible-core" = { version = "latest", uvx_args = "--with mitogen,requests" }
"pipx:ansible-creator" = "latest"
"pipx:httpie" = "latest"
"pipx:ipython" = "latest"
"pipx:molecule-plugins" = { version = "latest", uvx = "false", extras = "docker", pipx_args = "--include-deps" }
"pipx:trash-cli" = "latest"
cheat = "latest"
fastfetch = "latest"
mc = "latest"
neovim = "latest"
starship = "latest"
tmux = "3.7c"
usage = "latest"
yazi = "latest"

[settings]
auto_install = false
experimental = true
jobs = 6
not_found_auto_install = false
plugin_autoupdate_last_check_duration = '0'
prefer_offline = true

[settings.cargo]
binstall = true

[settings.status]
missing_tools = "never"

[settings.npm]
package_manager = "pnpm"

[env]
BINSTALL_DISABLE_TELEMETRY = true
